# Generated by Django 2.2.2 on 2019-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
    ]
