# Generated by Django 2.2.2 on 2019-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0002_auto_20190720_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='/', upload_to='media'),
            preserve_default=False,
        ),
    ]
