# Generated by Django 2.2.2 on 2019-07-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0004_auto_20190721_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='user_name',
        ),
    ]
