# Generated by Django 2.2.2 on 2019-07-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0006_user_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.FileField(upload_to='user_img'),
        ),
    ]
