# Generated by Django 2.2.2 on 2019-07-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0007_auto_20190722_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(upload_to='user_img'),
        ),
    ]
