# Generated by Django 2.2.2 on 2019-07-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0008_auto_20190722_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_img',
        ),
    ]
