# Generated by Django 2.2.2 on 2019-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0009_auto_20190722_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('price', models.FloatField(verbose_name='商品名称')),
                ('comments', models.CharField(max_length=300, verbose_name='商品介绍')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
            ],
        ),
    ]
