# Generated by Django 2.2.2 on 2019-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0010_goods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='price',
            new_name='goods_price',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_img',
            field=models.ImageField(default='', upload_to='goods_img'),
            preserve_default=False,
        ),
    ]
