# Generated by Django 2.2.2 on 2019-07-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0011_auto_20190722_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_img',
            field=models.ImageField(upload_to='goods_img', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.FloatField(verbose_name='商品价格'),
        ),
    ]
