# Generated by Django 2.2.2 on 2019-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0012_auto_20190723_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='comments',
            field=models.TextField(verbose_name='商品介绍'),
        ),
    ]
