# Generated by Django 2.2.2 on 2019-08-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0013_auto_20190730_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_title', models.CharField(max_length=20, verbose_name='大标题')),
                ('small_title', models.CharField(max_length=30, verbose_name='小标题')),
                ('context', models.TextField(verbose_name='内容')),
                ('advertisement_url', models.URLField(verbose_name='广告网址')),
                ('advertisement_img', models.ImageField(upload_to='advertisement_img', verbose_name='广告图片')),
            ],
            options={
                'verbose_name': '广告信息',
                'verbose_name_plural': '广告信息',
            },
        ),
    ]
