# Generated by Django 2.2.2 on 2019-08-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0014_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='big_title',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='big_title_grey',
            field=models.CharField(default='', max_length=10, verbose_name='大标题灰色字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='big_title_orange',
            field=models.CharField(default='', max_length=10, verbose_name='大标题橙色字'),
            preserve_default=False,
        ),
    ]
