# Generated by Django 2.2.2 on 2019-08-03 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0015_auto_20190801_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='last_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
