# Generated by Django 2.2.2 on 2019-08-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_platform', '0016_auto_20190803_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='评论内容')),
                ('goods_id', models.IntegerField(verbose_name='被评论商品ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='评论发布用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
            },
        ),
    ]
